---
fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 3.2       # default: RUBY_VERSION
default_ignores: false  # default: true

ignore: # default: []
  - '.*'
  - 'bin/**/*'
  - 'coverage/**/*'
  - 'gemfiles/**/*':
    - 'Security/Eval'
  - 'gemfiles/vendor/**/*'
  - 'sig/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
