dist: focal
language: ruby
cache: bundler
addons:
  apt:
    update: true
    packages:
      - libvips
      - libvips-dev
      - libvips-tools

before_install:
  - vips --version

rvm:
  - ruby-2.7
  - ruby-2.6
  - ruby-2.5
  - jruby
  - truffleruby

gemfile:
  - gemfiles/rails60_gems.rb
  - gemfiles/rails52.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails42.gemfile

env:
  global:
    - JRUBY_OPTS="--dev --debug"
    - COVERAGE="enabled"

jdk: openjdk14

jobs:
  fast_finish: true
  allow_failures:
    - rvm: truffleruby
