# frozen_string_literal: true

# Legacy Capybara::Screenshot / Capybara::Screenshot::Diff config surface.
#
# Nothing but requires is left here. The storage is SnapDiff::Config
# (ADR-008 step 1, the require leaf of the config graph); the derived values
# (active?, screenshot_area, default_options) live there too since step 7b;
# and the old accessor names, Diff.configure/.compare, SnapDiff.start and
# the AVAILABLE_DRIVERS alias are generated by snap_diff/legacy_shims -- the
# one file that holds the v1 surface as code, so that the canonical core
# needs nothing from this tree and 3.0 can delete both together. The v1
# surface (Capybara::Screenshot.window_size = ..., Diff.configure { ... },
# Diff.compare) keeps working unchanged: one storage, two views.
#
# Load order: requiring snap_diff/config first also eagerly evaluates the
# require-time defaults (ENV["CI"] for fail_if_new, Rails.root/pwd for
# root) at this same load moment, exactly when the old mattr_accessor
# default blocks used to run. Neither file requires back here, so the graph
# stays acyclic.
require "snap_diff/config"
require "snap_diff/legacy_shims"
