module Capybara
  module Screenshot
    module Diff
      module Reporters
        class Default < Base
          @annotated_base_image_path: Pathname
          @annotated_image_path: Pathname
          @difference: Difference

          attr_reader annotated_base_image_path: Pathname
          attr_reader annotated_image_path: Pathname

          attr_reader difference: Difference

          def annotate_and_save_images: -> void

          def annotate_and_save_image: (ImageCompare::image_entity, TestMethods::path_entity) -> void

          DIFF_COLOR: [255, 0, 0, 255]

          def annotate_difference: (ImageCompare::image_entity, Region) -> void

          SKIP_COLOR: [255, 192, 0, 255]

          def annotate_skip_areas: (ImageCompare::image_entity, Array[Region] skip_areas) -> void

          def build_error_message: -> ::String

          def clean_tmp_files: () -> void
        end
      end
    end
  end
end
