module Capybara
  module Screenshot
    module Diff
      module Drivers
        class BaseDriver[ImageEntity]
          type images_entity[out T] = [T, T]
          type dimension_entity = [Numeric, Numeric]

          type options_entity = {
              area_size_limit?: Numeric?,
              color_distance_limit?: Numeric?,
              driver: (:auto | :vips | :chunky_png)?,
              dimensions: dimension_entity?,
              median_filter_window_size: Numeric?,
              shift_distance_limit?: Numeric?,
              skip_area?: Array[Region]?,
              stability_time_limit?: Numeric?,
              tolerance?: Numeric?,
              wait?: Numeric?
            }

          type color = [Integer, Integer, Integer, Integer]

          attr_reader new_file_name: String

          attr_reader old_file_name: String

          attr_reader options: options_entity

          def initialize: (String new_file_name, String old_file_name, ?options_entity options) -> void

          def skip_area=: (Array[Region] new_skip_area) -> void

          # Resets the calculated data about the comparison with regard to the "new_image".
          # Data about the original image is kept.
          def reset: () -> void

          def shift_distance_equal?: () -> bool

          def shift_distance_different?: () -> bool

          def find_difference_region: (ImageEntity new_image, ImageEntity old_image, Numeric color_distance_limit, Numeric _shift_distance_limit, Integer _area_size_limit, ?fast_fail: bool) -> [Region?, (ImageEntity | top | nil)]

          def adds_error_details_to: (::Hash[Symbol, untyped] _log) -> void

          def inscribed?: (dimension_entity dimensions, ImageEntity i) -> bool

          def crop: (Region region, ImageEntity i) -> ImageEntity

          def filter_image_with_median: (ImageEntity image, Numeric median_filter_window_size) -> ImageEntity

          def add_black_box: (ImageEntity memo, Region region) -> void

          def difference_level: (Vips::Image diff_mask, ImageEntity old_img, Region _region) -> Float

          def image_area_size: (ImageEntity old_img) -> Integer

          def height_for: (ImageEntity image) -> Integer

          def width_for: (ImageEntity image) -> Integer

          # Vips could not work with the same file. Per each process we require to create new file
          def save_image_to: (ImageEntity image, String filename) -> void

          def resize_image_to: (ImageEntity image, Integer new_width, Integer new_height) -> ImageEntity

          def load_images: (String old_file_name, String new_file_name) -> images_entity[ImageEntity]

          def from_file: (String filename) -> ImageEntity

          def dimension_changed?: (ImageEntity old_image, ImageEntity new_image) -> bool

          def dimension: (ImageEntity image) -> dimension_entity

          def draw_rectangles: (images_entity[ImageEntity] images, Region region, color rgba, Integer offset) -> void
        end
      end
    end
  end
end
