module Capybara
  class Result
    def map: () -> Result
  end

  module Screenshot
    module BrowserHelpers
      def self.current_capybara_driver_class: () -> top

      def self.selenium?: () -> boolish?

      def self.window_size_is_wrong?: () -> boolish

      def self.bounds_for_css: (*String css_selectors) -> Array[Region::raw_region_entity]

      IMAGE_WAIT_SCRIPT: String

      def self.pending_image_to_load: () -> top?

      HIDE_CARET_SCRIPT: String

      def self.hide_caret: () -> void

      FIND_ACTIVE_ELEMENT_SCRIPT: String

      type capybara_element = top

      def self.blur_from_focused_element: () -> capybara_element?

      GET_BOUNDING_CLIENT_RECT_SCRIPT: String

      def self.all_visible_regions_for: (String selector) -> Array[Region::raw_region_entity]

      def self.region_for: (Result element) -> Region::raw_region_entity
    end
  end
end
