module Capybara
  module Screenshot
    module Diff
      module Utils
        def self.detect_available_drivers: () -> Array[(:vips | :chunky_png)]

        def self.find_driver_class_for: [T] (Symbol driver) -> T

        def self.detect_test_framework_assert: [T < Exception] () -> T
      end
    end
  end
end
