module Capybara
  module Screenshot
    module Diff
      class Comparison
        attr_accessor new_image: ImageCompare::image_entity
        attr_accessor base_image: ImageCompare::image_entity
        attr_accessor options: Drivers::BaseDriver::options_entity
        attr_accessor driver: ImageCompare::driver_entity
        attr_accessor new_image_path: Pathname
        attr_accessor base_image_path: Pathname
      end
    end
  end
end
