module Capybara
  module Screenshot
    def self.root=: ((String | Pathname) path) -> Pathname

    def self.root: -> Pathname

    def self.active?: () -> boolish

    def self.screenshot_area: () -> String

    def self.screenshot_area_abs: () -> Pathname

    # Module to track screen shot changes
    module Diff
      AVAILABLE_DRIVERS: Array[(:vips | :chunky_png)]

      ASSERTION: (top | RuntimeError)

      def self.default_options: () -> ScreenshotMatcher::input_options

      def self.included: (top klass) -> void

      private

      def track_failures: (Array[untyped] screenshots) -> void
    end
  end
end
