module Capybara
  module Screenshot
    module Diff
      class Difference
        attr_reader comparison: ImageCompare::Comparison

        def different?: () -> bool

        def base_image: () -> top

        def options: () -> Drivers::BaseDriver::options_entity

        def tolerance: () -> Numeric?

        def area_size_limit: () -> Numeric?

        def blank?: () -> bool

        def region_area_size: () -> Numeric

        def ratio: () -> Numeric?

        def to_h: () -> Hash[Symbol, untyped]

        def coordinates: () -> Region::raw_region_entity

        def inspect: () -> String

        def tolerable?: () -> bool
      end
    end
  end
end
