module Capybara
  module Screenshot
    module Diff
      LOADED_DRIVERS: { vips: ImageCompare::driver_entity, chunky_png: ImageCompare::driver_entity }

      # Compare two images_entities and determine if they are equal, different, or within some comparison
      # range considering color values and difference area size.
      class ImageCompare
        TOLERABLE_OPTIONS: [:tolerance, :color_distance_limit, :shift_distance_limit, :area_size_limit]

        type driver_entity = (Drivers::VipsDriver | Drivers::ChunkyPNGDriver)
        type image_entity = (ChunkyPNG::Canvas | Vips::Image)
        type images_entities = [image_entity, image_entity]
        type cache_entity = (::Hash[Symbol, top] | top)
        type reporter_entity = (Reporters::Base | Reporters::Default)

        @comparison: Comparison?
        @difference: Difference
        @error_message: String?

        @reporter: reporter_entity?

        attr_reader difference: Difference?
        attr_reader error_message: String?
        attr_reader base_image_path: Pathname
        attr_reader image_path: Pathname
        attr_reader driver: driver_entity
        attr_reader driver_options: Drivers::BaseDriver::options_entity
        attr_reader skip_area: Array[Region]?
        attr_accessor shift_distance_limit: Numeric?
        attr_accessor area_size_limit: Numeric?
        attr_accessor color_distance_limit: Numeric?

        @median_filter_window_size: Numeric?
        @dimensions: Drivers::BaseDriver::dimension_entity?
        @tolerance: Numeric?

        def initialize: (TestMethods::path_entity new_file_name, TestMethods::path_entity old_file_name, ?Drivers::BaseDriver::options_entity options) -> void

        def self.build: (TestMethods::path_entity new_file_name, TestMethods::path_entity old_file_name, ?Drivers::BaseDriver::options_entity options) -> ImageCompare

        # Compare the two image_entity files and return `true` or `false` as quickly as possible.
        # Return falsely if the old file does not exist or the image_entity dimensions do not match.
        def quick_equal?: () -> boolish

        # Compare the two images_entities referenced by this object, and return `true` if they are different,
        # and `false` if they are the same.
        def different?: () -> bool

        def reporter: -> ::Capybara::Screenshot::Diff::ImageCompare::reporter_entity

        def processed?: -> bool

        def processed: -> ImageCompare

        private

        %a{rbs:test:skip} def blur_image_by: (Vips::Image, Numeric) -> image_entity

        def build_comparison: -> Comparison

        def difference=: (Difference) -> void

        def failed_difference: (Comparison, top) -> Difference

        def find_difference: -> Difference

        def image_files_exist?: -> boolish

        def load_and_process_images: -> Comparison

        def median_filter_window_size: -> Numeric?

        def new_file_size: () -> Integer

        def no_difference: (Comparison?) -> Difference

        def old_file_size: () -> Integer

        def preprocess_image: (image_entity image) -> image_entity

        def preprocess_images: (images_entities images) -> images_entities

        def require_images_exists!: -> void

        def without_tolerable_options?: -> boolish
      end
    end
  end
end
