# Add the `screenshot` method to ActionDispatch::IntegrationTest
module Capybara
  module Screenshot
    module Diff
      module TestMethods
        type name_entity = (Symbol | String)
        type path_entity = (string | Pathname)

        @screenshot_counter: Numeric?
        @screenshot_group: String?
        @screenshot_section: String?
        @test_screenshot_errors: Array[top]?
        @test_screenshots: Array[[Array[String]?, String, ImageCompare]]?

        def initialize: (*untyped) -> untyped

        def group_parts: () -> Array[String]

        def build_full_name: (name_entity name) -> String

        def schedule_match_job: ([untyped, untyped, untyped] job) -> true

        def screenshot_dir: () -> String

        def screenshot_section: (name_entity name) -> void

        def screenshot_group: (name_entity? name) -> void

        def screenshot: (name_entity name, ?skip_stack_frames: ::Integer, **untyped options) -> boolish

        def assert_image_not_changed: (Array[String] caller, String name, ImageCompare comparison) -> ::String?

        private

        def build_screenshot_matches_job: (String, Drivers::BaseDriver::options_entity) -> ScreenshotMatcher::job_entity?
      end
    end
  end
end
