module Capybara
  module Screenshot
    module Diff
      module Vcs
        SILENCE_ERRORS: String

        def self.checkout_vcs: (Pathname screenshot_path, Pathname checkout_path) -> bool

        def self.restore_git_revision: (Pathname screenshot_path, Pathname checkout_path) -> bool

        def self.restore_svn_revision: -> bool

        def self.svn?: -> bool
      end
    end
  end
end
