module Capybara
  module Screenshot
    module Diff
      module Vcs
        SILENCE_ERRORS: String

        def restore_git_revision: (String name, String target_file_name) -> void

        def checkout_vcs: (String name, String old_file_name, String new_file_name) -> void
      end
    end
  end
end
